server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
loging:
  level:
    com.koreait.exam.chat_25_06: debug
